# Generated by Django 3.0.5 on 2025-02-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
